### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by spg1004-a** [spg1004-a/GESPRO_PracticaGestionTareas_2021#26]
Publicar aplicación completada en Google Play.

**Comment by mgs1005** [comment]
![image](https://user-images.githubusercontent.com/74243154/100445547-8f80f200-30ad-11eb-8ce7-ea01bfe1fe5b.png)
![image](https://user-images.githubusercontent.com/74243154/100445553-94de3c80-30ad-11eb-831f-81b647379910.png)
![image](https://user-images.githubusercontent.com/74243154/100445576-9e67a480-30ad-11eb-9ca9-ec21c58715b4.png)
![image](https://user-images.githubusercontent.com/74243154/100445596-a58eb280-30ad-11eb-952a-4e012006aa86.png)
![image](https://user-images.githubusercontent.com/74243154/100445605-ab849380-30ad-11eb-9718-b871e9259da3.png)
![Uploading image.png…]()

**Comment by mgs1005** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
