### ISSUE TITLE
Grabar discos 

### ISSUE THREAD

**Issue by spg1004-a** [spg1004-a/GESPRO_PracticaGestionTareas_2021#35]
Grabación de discos.

**Comment by mgs1005** [comment]
- - Código fuente app
- - Ejecutable app
- - Herramientas
- - Plataforma de desarrollo del algoritmo
- - Herramienta de conteo de abejas
- Documentación
- Memoria
- Anexos
- JavaDoc
- Dataset de videos
- README
- Repositorio GoBees
- Repositorio prototipos
- Repositorio dependencia OpenCV
