### ISSUE TITLE
Crear página web

### ISSUE THREAD

**Issue by spg1004-a** [spg1004-a/GESPRO_PracticaGestionTareas_2021#37]
Crear página web

**Comment by mgs1005** [comment]
https://startbootstrap.com/template-overviews/new-age/
http://www.grabon.in/mobile-apps/

http://bronto.github.io/javasphinx/

**Comment by mgs1005** [comment]
Add Google Play link #96

**Comment by mgs1005** [comment]
Update .gitignore #96

**Comment by mgs1005** [comment]
Finish website #96

**Comment by mgs1005** [comment]
Minor fixes and compress imgs

**Comment by mgs1005** [comment]
Minor changes

**Comment by mgs1005** [comment]
Minor changes

**Comment by mgs1005** [comment]
Add docs link

**Comment by mgs1005** [comment]
http://gobees.io/
